eureka:
  server:
    eviction-interval-timer-in-ms: 15000
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    hostname: ${eureka_host:localhost}
#     secure-port: ${server.port}
#     non-secure-port-enabled: true
#     non-secure-port: ${server.port}
